---
version: "3.7"

# HTTP-Potal用の設定
services:
  # 通信を暗号化
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - pleasanter-web
    restart: always
    environment:
      DOMAINS: "wordpress.example.com -> http://pleasanter-web"
      # 本番モードへ切り替え
      # STAGE: 'production'
      # 証明書を強制的に再取得する
      # FORCE_RENEW: 'true'
      # 容量設定
      #  CLIENT_MAX_BODY_SIZE: 0  # これだと無制限
      CLIENT_MAX_BODY_SIZE: 500M
      # HTTP強制
      HSTS_MAX_AGE: 60 # 秒
      # ログ出力設定
      ERROR_LOG: stdout
      ACCESS_LOG: stderr
      # 鍵は再利用
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ssl_data:/var/lib/https-portal
      # IPアドレス制限用
      - ./images/steveltn/https-portal/dynamic-env:/var/lib/https-portal/dynamic-env
    networks:
      - pleasanter-service-network

volumes:
  ssl_data:
    driver:
      local
      # Compose の外ですでに作成済みの volume を指定する場合は ture を設定する。
      # そうすると、 docker-compose up 時に Compose は volume を作成しようとしません。
      # かつ、指定した volume が存在しないとエラーを raise します。
      # external: true
networks:
  # 他のcomposerと連携できるように、
  # ネットワーク名を明示的に設定する
  pleasanter-service-network:
