version: "3.7"

services:
  postgres-db:
    build: postgres/.
    container_name: db-container 
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword1234
      - PGPASSWORD=mysecretpassword1234
      - POSTGRES_DB=testdb
      - DATABASE_HOST=localhost
      - DB_EXTENSION=pg_trgm
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
  pleasanter-web:
#    ports:
#      - "80:80"
    build:
      context: pleasanter/.
      args:
      # バージョンを指定
      # 1.1.3.2 : cea284d8c57f4794da821c76d5676d0078b30ae0
          - GIT_HASH=cea284d8c57f4794da821c76d5676d0078b30ae0
  # 通信を暗号化
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - pleasanter-web
    restart: always
    environment:
      DOMAINS: 'wordpress.example.com -> http://pleasanter-web'
      # 本番モードへ切り替え
      # STAGE: 'production'
      # 証明書を強制的に再取得する
      # FORCE_RENEW: 'true'
      # 容量設定
      #  CLIENT_MAX_BODY_SIZE: 0  # これだと無制限
      CLIENT_MAX_BODY_SIZE: 500M 
      # HTTP強制
      HSTS_MAX_AGE: 60 # 秒 
      # ログ出力設定
      ERROR_LOG: stdout
      ACCESS_LOG: stderr
      # 鍵は再利用
    volumes:
    - ssl_data:/var/lib/https-portal

volumes:
  db-data:
   driver: local
  ssl_data:
   driver: local
    # Compose の外ですでに作成済みの volume を指定する場合は ture を設定する。
    # そうすると、 docker-compose up 時に Compose は volume を作成しようとしません。
    # かつ、指定した volume が存在しないとエラーを raise します。
    #external: true